services:
  finapi:
    build:
      context: .
      dockerfile: FinPulse.Api/Dockerfile
    image: finapi
    container_name: finapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Otel__ExporterEndpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - Jwt__Issuer=${JWT_ISSUER:-FinPulse.Api}
      - Jwt__Audience=${JWT_AUDIENCE:-FinPulse.Api}
      - Jwt__ExpirationMinutes=${JWT_EXPIRATION_MINUTES:-60}
      - Cookie__Secure=${COOKIE_SECURE:-false}
      - Bot__ApiKey=${BOT_API_KEY}
    ports:
      - "${API_PORT:-5026}:8080"
    networks:
      - fin-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  fin-network:
    driver: bridge